create table t_moyenne_sql(
    id int not null primary key,
    matricule varchar(7),
    nom varchar(15) not null,
    postnom varchar(15) not null,
    prenom varchar(15) not null,
    genre char(1),
    `int 1/26` float null,
    `td /5` float null,
    `td /15` float null,
    `bon`  float null,
    `int` float null,
    `int.3 /10` float null,
    `bon /3` float null,
    `bon /2` float null,
    `INT /7` float null,
    `TDs /2` float null,
    `BON /1` float null,
    `Moyenne /10` int
);
